version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=YourStrongPassword
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000" # Примерный порт для вашего приложения, измените по необходимости
    environment:
      - DB_HOST=db
      - DB_PORT=1433
      - DB_USER=sa
      - DB_PASSWORD=YourStrongPassword
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis